controller:
  service:
    annotations:
#      service.beta.kubernetes.io/do-loadbalancer-hostname: ${base_domain}
      service.beta.kubernetes.io/do-loadbalancer-name: ${base_domain}
      service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: true
