version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana
    networks:
      - elastic
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3001:3000

volumes:
  elastic:
  grafana:

networks:
  elastic:
